version: '2.4'
services:
  bombardier:
    build: main-application
    environment:
      - PYTHONUNBUFFERED=1
      - NO_BENCHMARK=1
    mem_limit: 4096m
    cpus: 4.0
    depends_on:
      - solr
      - varnish
  zookeeper:
    image: zookeeper:3.4
    hostname: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: 'server.1=zookeeper:2888:3888'
    command: sh -c "zkServer.sh start && tail -f /dev/null"
  solr:
    image: solr:8.11
    hostname: solr
    ports:
      - 25900:8983
    command: sh -c "bin/solr start -q && tail -f /dev/null"
    environment:
      ZK_HOST: 'zookeeper'
      SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
    depends_on:
      - zookeeper
  varnish:
    image: varnish:stable
    container_name: varnish
    volumes:
      - "./varnish.vcl:/etc/varnish/default.vcl"
    ports:
      - 25901:80
    depends_on:
      - solr
