[package]
name = "actix_web"
version = "0.0.1"
edition = "2018"

[dependencies]
actix-web = "3.0"
paperclip = { version = "0.6", features = ["actix", "swagger-ui"] }
serde = "1.0"
serde_json = "1.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3